### ISSUE TITLE
希望增加 Tidal应用的分流规则

### ISSUE THREAD

**Issue by ltdstudio** [fanmingming/Rules#1]
速度很快，很喜欢，希望增加 tidal的 分流规则。

**Comment by fanmingming** [comment]
`HOST-SUFFIX,tidal-cms.s3.amazonaws.com,TIDAL
HOST-SUFFIX,tidal.com,TIDAL
HOST-SUFFIX,tidalhifi.com,TIDAL
HOST-SUFFIX,wimpmusic.com,TIDAL
USER-AGENT,TIDAL*,TIDAL
USER-AGENT,TIDAL*dia,TIDAL`
编辑配置文件，添加上面内容。将每行后面的TIDAL替换为你要使用的地区即可。比如US！
